version: '3.8'

services:
  app:
    container_name: next-app
    build:
      context: .
      target: runner
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
